package io.vela.core.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The normalised emulator catalogue generated by `scripts/build_emulator_catalog.py` from the
 * Daijishō platform definitions (MIT) and ES-DE's Android find rules (MIT). It is a versioned
 * asset (`catalog/emulators.json`); the app never downloads it. See NOTICE for attribution.
 *
 * This is reference data about how third-party emulators are launched. Vela's own launch
 * recipes remain `players.json` ([PlayerDefinition]); this catalogue is consulted, never guessed.
 */
@Serializable
data class LaunchCatalog(
    val schemaVersion: Int,
    val generatedAt: String,
    val sources: List<CatalogSource> = emptyList(),
    val platforms: List<CatalogPlatform> = emptyList(),
    /** Package/activity pairs ES-DE knows, by ES-DE emulator name; used to cross-check recipes. */
    val knownActivities: List<KnownActivity> = emptyList(),
    /** Everything the generator could not understand completely. Nothing was dropped because of it. */
    val warnings: List<CatalogWarning> = emptyList(),
)

@Serializable
data class CatalogSource(
    val id: String,
    val name: String,
    val url: String,
    val revision: String,
    val license: String,
    val copyright: String,
)

@Serializable
data class CatalogPlatform(
    val id: String,
    val name: String,
    val shortName: String? = null,
    /** Union of the extensions its emulators accept, lowercase, without the dot. */
    val extensions: List<String> = emptyList(),
    val acceptedFilenameRegex: String? = null,
    val source: String,
    val emulators: List<CatalogEmulator> = emptyList(),
)

/** One way to launch one emulator for one platform. */
@Serializable
data class CatalogEmulator(
    val id: String,
    val name: String,
    val extensions: List<String> = emptyList(),
    @SerialName("package") val packageName: String? = null,
    /** Fully qualified activity class, or null when the recipe names only a package. */
    val activity: String? = null,
    val action: String? = null,
    /** How the game reaches the emulator: `uri`, `path`, `both` or `none`. */
    val dataType: String,
    /** Value of `-d`, usually a placeholder such as `{file.uri}`. */
    val data: String? = null,
    val mimeType: String? = null,
    val categories: List<String> = emptyList(),
    val extras: List<CatalogExtra> = emptyList(),
    /** `Intent.FLAG_*` names (from `--activity-*` options or a numeric `-f`). */
    val flags: List<String> = emptyList(),
    /** `-S` in the recipe: force-stop the package before starting. */
    val forceStopBeforeLaunch: Boolean = false,
    /** Daijishō's `killPackageProcesses`: the frontend kills the emulator when the game ends. */
    val killProcess: Boolean = false,
    /** Neither source states this; kept for future data. */
    val requiresBios: Boolean? = null,
    /** Placeholders found in the recipe: `{file.uri}`, `{file.path}`, `{tags.*}`... */
    val placeholders: List<String> = emptyList(),
    /** True when ES-DE lists the same package/activity pair; null when ES-DE data was unavailable. */
    val esdeVerified: Boolean? = null,
    val source: String,
    /** The original `amStartArguments`, untouched. */
    val raw: String,
    val notes: String? = null,
    val warnings: List<String> = emptyList(),
)

@Serializable
data class CatalogExtra(
    val key: String,
    /** `string`, `boolean`, `int`, `long`, `float`, `uri`, `component`, `string[]`, `int[]`, `long[]`, `float[]`, list variants or `null`. */
    val type: String,
    val value: String? = null,
)

@Serializable
data class KnownActivity(
    val emulator: String,
    @SerialName("package") val packageName: String,
    val activity: String,
)

@Serializable
data class CatalogWarning(
    val platform: String? = null,
    val emulator: String? = null,
    val message: String,
)
